geral:
  abs_path: /home/yoshraf/projects/master-analysis-inequality-mobility/inequality-mobility/
  EPSG: 31983
geodata:
  metro: data/01_raw/gis/SAD69-96_SHP_estacaometro.zip!SAD69-96_SHP_estacaometro/SAD69-96_SHP_estacaometro_point.shp
  trem: data/01_raw/gis/SAD69-96_SHP_estacaotrem.zip!SAD69-96_SHP_estacaotrem/SAD69-96_SHP_estacaotrem_point.shp
  ciclovia: data/01_raw/gis/SAD69-96_SHP_redecicloviaria.zip!SAD69-96_SHP_redecicloviaria/SAD69-96_SHP_redecicloviaria.shp
  ilumina: data/01_raw/gis/SAD69-96_SHP_iluminacaopublica.zip!SAD69-96_SHP_iluminacaopublica/SAD69-96_SHP_iluminacaopublica.shp
  ponto_onibus: data/01_raw/gis/SAD69-96_SHP_pontoonibus.zip!SAD69-96_SHP_pontoonibus/SAD69-96_SHP_pontoonibus.shp
  ponto_cotado: data/01_raw/gis/PONTO_COTADO.zip!sad6996_PONTO_COTADO_INTERVIA.shp
  terminal: data/01_raw/gis/terminal_onibus.zip!sad6996_terminal_onibus.shp
  od2023: data/01_raw/Banco2023_divulgacao_190225.sav
  od2017: data/01_raw/OD_2017.sav
  od2007: data/01_raw/OD_2007_v2d.sav
  # external
  acess_empregos_ti: data/01_raw/external/Acessibilidade.zip!Acessibilidade/Acessibilidade_Empregos/Zonas_OD2017_Acc_60Min_Empregos_TI_Qua_7AM.shp
  acess_empregos_tp: data/01_raw/external/Acessibilidade.zip!Acessibilidade/Acessibilidade_Empregos/Zonas_OD2017_Acc_60Min_Empregos_TP_Qua_7AM.shp
  acess_lazer_ti: data/01_raw/external/Acessibilidade.zip!Acessibilidade/Acessibilidade_Lazer/Zonas_OD2017_Acc_30Min_Lazer_TI_Dom_10AM.shp
  acess_lazer_tp: data/01_raw/external/Acessibilidade.zip!Acessibilidade/Acessibilidade_Lazer/Zonas_OD2017_Acc_30Min_Lazer_TP_Dom_10AM.shp
  censo_demo: data/01_raw/external/Acessibilidade.zip!Acessibilidade/Classes_Socio-ocupacionais_raca/SC_2010_Raca_Renda.shp
features:
  censo_demo:
    features:
      - alta_branc
      - alta_negro
      - alta_outro
      - media_bran
      - media_negr
      - media_outr
      - baixa_bran
      - baixa_negr
      - baixa_outr
  od2007:
    features:
      Zona de Domicílio: zona_do_domicilio
      Município do Domicílio: municipio_de_domicilio
      Coordenada X Domicílio: coordenada_x_do_domicilio
      Coordenada Y Domicílio: coordenada_y_do_domicilio
      Coordenada X Origem: coordenada_x_origem
      Coordenada Y Origem: coordenada_y_origem
      Coordenada X Destino: coordenada_x_destino
      Coordenada Y Destino: coordenada_y_destino
      Identifica Domicílo: identifica_domicilo
      Data da Entrevista: data_da_entrevista
      Número de Moradores no Domicílio: total_de_moradores_do_domicilio
      Quantidade Automóvel: quantidade_de_automoveis
      Renda Familiar Mensal: renda_familiar_mensal 
      Identifica Pessoa: identifica_pessoa
      Situação Familiar: situacao_familiar
      Idade: idade_em_anos
      Gênero: sexo
      Número da Viagem: numero_de_ordem_do_registro
      Total de Viagens internas: total_de_viagens_da_pessoa
      Motivo no Destino: motivo_no_destino
      Modo Principal: modo_principal_da_viagem
  od2017:
    features:
      # Domicílio
      - Município do domicílio
      - Zona de domicílio
      - Coordenada X domicílio
      - Coordenada Y domicílio
      - Identifica domicílo
      - Data da entrevista
      - Tipo de domicílio
      - Possui água encanada?
      - A rua é pavimentada?
      - Total de famílias no domicílio
      - Total de moradores na família
      - Condição de moradia # Própria
      - Quantidade de banheiros
      - Quantidade de empregados domésticos
      - Quantidade de automóveis
      - Quantidade de motocicletas
      - Quantidade de bicicletas
      - Critério de Classificação Econônica Brasil
      - Pontos Critério Brasil
      - Renda familiar mensal
      # Pessoa
      - Identifica pessoa # ID Pessoa
      - Situação familiar # Responsável/Conjugue
      - Idade
      - Gênero
      - Estuda atualmente?
      - Grau de instrução
      - Condição de atividade
      - Valor da renda individual
      # Viagem
      - Número da viagem
      - Dia da Semana
      - Total de viagens da pessoa
      - Coordenada X Origem
      - Coordenada Y Origem
      - Coordenada X Destino
      - Coordenada Y Destino
      - Motivo na Origem
      - Motivo no Destino
      - Servir passageiro na Origem
      - Servir passageiro no Destino
      - Modo 1
      - Modo 2
      - Modo 3
      - Modo 4
      - Hora Saída
      - Minuto Saída
      - Tempo Andando na Origem
      - Hora Chegada
      - Minuto Chegada
      - Tempo Andando no Destino
      - Duração da Viagem (em minutos)
      - Modo Principal
      - Número de ordem do registro #ID
  od2023:
    features:
      # Domicílio
      - municipio_de_domicilio
      - zona_do_domicilio
      - coordenada_x_do_domicilio
      - coordenada_y_do_domicilio
      - identifica_domicilo
      - data_da_entrevista
      - tipo_de_domicilio
      - possui_agua_encanada
      - a_rua_e_pavimentada
      - total_de_familias_no_domicilio
      - total_de_moradores_do_domicilio
      - condicao_de_moradia
      - quantidade_de_banheiros
      - quantidade_de_empregados
      - quantidade_de_automoveis
      - quantidade_de_motocicletas
      - quantidade_de_bicicletas
      - criterio_de_classificacao_econonica_brasil
      - pontuacao_do_criterio_brasil
      - renda_familiar_mensal
      # Pessoa
      - identifica_pessoa # ID Pessoa
      - situacao_familiar # Responsável/Conjugue
      - idade_em_anos
      - sexo
      # - raca/cor
      - estuda_atualmente
      - grau_de_instrucao
      - condicao_de_atividade
      - valor_da_renda_individual
      # Viagem
      - numero_da_viagem
      - dia_da_semana
      - total_de_viagens_da_pessoa
      - coordenada_x_origem
      - coordenada_y_origem
      - coordenada_x_destino
      - coordenada_y_destino
      - motivo_na_origem
      - motivo_no_destino
      - servir_passageiro_na_origem
      - servir_passageiro_no_destino
      - modo_1
      - modo_2
      - modo_3
      - modo_4
      - hora_de_saida
      - minuto_de_saida
      - tempo_andando_na_origem
      - hora_de_chegada
      - minuto_de_chegada
      - tempo_andando_no_destino
      - duracao_da_viagem_em_minutos
      - modo_principal_da_viagem
      - numero_de_ordem_do_registro #ID
  od2017_socio:
    bens:
      - Quantidade de automóveis
      - Quantidade de motocicletas
      - Quantidade de bicicletas
      - Renda familiar mensal
    per: Total de moradores na família
  od2023_socio:
    bens:
      - quantidade_de_automoveis
      - quantidade_de_motocicletas
      - quantidade_de_bicicletas
      - renda_familiar_mensal
    per: total_de_moradores_do_domicilio
  diff-in-diffs:
    od2007:
      zone:
        cluster_perif:
          - 46 # Água Rasa
          - 240 # Linhas Corrente
          - 241 # Vila Ema
          # - 200 # Vila Formosa
          # News
          - 238 # Orfanato
          - 239 # Vila Zelina
          - 237 # Tamanduatei
          - 228 # Vila Carioca
          # - 230 # Vila Heliópolis + (São João Climatico)
          # - 223 # Sacomã
          - 222 # Ipiranga
          - 227 # Vila Independencia
        cluster_center:
          - 81 # Pinheiros
          - 79 # Jardim Paulistano
          - 80 # Jardim Europa
          - 95 # Alto de Pinheiros
          # - 75 # Jardins
          # - 82 # Vila Madalena
          - 67 # Chácara Itaim
          - 295 # Morumbi
          - 296 # Jóquei Clube
          - 317 # Cidade Universitária
          - 318 # Butanta
          - 319 # Jardim Caxingui

    od2017:
      zone:
        cluster_perif:
          - 46 # Água Rasa
          - 256 # Linhas Corrente
          - 257 # Vila Ema
          # - 211 # Vila Formosa
          # News
          - 254 # Orfanato
          - 255 # Vila Zelina
          - 253 # Tamanduatei
          - 242 # Vila Carioca
          # - 244 # Vila Heliópolis
          # - 245 # Vila Heliópolis (São João Climatico)
          # - 237 # Sacomã
          - 236 # Ipiranga
          - 241 # Vila Independencia
        cluster_center:
          - 82 # Pinheiros
          - 80 # Jardim Paulistano
          - 81 # Jardim Europa
          - 96 # Alto de Pinheiros
          # - 76 # Jardins
          # - 83 # Vila Madalena
          - 68 # Chácara Itaim
          - 317 # Jóquei Clube
          - 316 # Morumbi
          - 339 # Cidade Universitária
          - 340 # Butantã
          - 341 # Jardim Caxingui
    subway:
      - ORATÓRIO
      - FRADIQUE COUTINHO
      - FARIA LIMA
      - PINHEIROS
      - BUTANTÃ
      - VILA PRUDENTE
      - TAMANDUATEÍ
      - SACOMÃ
    distance:
      treatment: 600
      treatment-max: 2000
  did:
    subway:
      entre_07e17:
        central:
          - FRADIQUE COUTINHO
          - FARIA LIMA
          - PINHEIROS
          - BUTANTÃ
        periferia:
          - ORATÓRIO
          - VILA PRUDENTE
          - TAMANDUATEÍ
          - SACOMÃ
      entre_17e23:
        central:
          - CAMPO BELO
          - HOSPITAL SÃO PAULO
          - AACD-SERVIDOR
          - MOEMA
          - EUCALIPTOS
        periferia:
          # DURANTE
          # - SÃO LUCAS
          # - CAMILO HADDAD
          # - VILA TOLSTÓI
          # - VILA UNIÃO
          # POS
          - JARDIM PLANALTO
          - SAPOPEMBA
          - FAZENDA DA JUTA
          - SÃO MATEUS
          # - JARDIM COLONIAL
          - VILA SÔNIA
model_input:
  discrete_choice:
    columns:
      # Domicílio
      - zona_do_domicilio
      - data_da_entrevista
      - coordenada_x_do_domicilio
      - coordenada_y_do_domicilio
      # Pessoa
      - identifica_pessoa
      # - Situação familiar # Responsável/Conjugue
      - idade_em_anos
      - sexo
      # Viagem
      # - Dia da Semana
      - total_de_viagens_da_pessoa
      - motivo_no_destino
      - hora_de_saida
      # Novas Variáveis Gis
      - loc_origem_dist_metro
      - loc_origem_dist_trem
      - loc_origem_dist_term
      - loc_origem_dist_ciclo
      - loc_destino_dist_metro
      # Bens per capita
      - per_quantidade_de_automoveis
      - per_quantidade_de_motocicletas
      - per_quantidade_de_bicicletas
      - per_renda_familiar_mensal
      # Final
      - dist_od
    idx:
      - identifica_pessoa
      - zona_do_domicilio
      - data_da_entrevista
      - coordenada_x_do_domicilio
      - coordenada_y_do_domicilio
    label:
      column: modo_principal_da_viagem
      values:
        - A pé
        - Automóvel
        - Ônibus
        - Metrô/Trem
        - Ônibus+Metrô/Trem
        - Metrô/Trem+Ônibus
        - Transporte escolar
        - Taxi/Taxi App
        - Motocicleta
        - Bicicleta
        # - Metrô/Trem+Automóvel
        - Outros
    encoding:
      # Motivo no Destino:
      #   - Pessoa responsável
      #   - Filho(a)/ enteado(a)
      #   - Conjugê/ companheiro(a)
    categorical:
      - sexo
      - motivo_no_destino

modeling:
  map_class:
    A pé: 0
    Automóvel: 1
    Bicicleta: 2
    Metrô/Trem: 3
    Metrô/Trem+Ônibus: 4
    Motocicleta: 5
    Outros: 6
    Taxi/Taxi App: 7
    Transporte escolar: 8
    Ônibus: 9